[toolchain]
anchor_version = "0.28.0"
solana_version = "1.18.2"

[features]
resolution = true
skip-lint = false

[programs.localnet]
monopoly_world = { path = "programs/monopoly-world", address = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS" }
movement = { path = "programs/systems/movement", address = "8UP7Ezw5qK7eRaLstChu9QVBzku7G6aGK5gQsSQrvB4R" }
position = { path = "programs/components/position", address = "BKFBy41BBf45X2RQZCBP7Jk3SH6FpXtnN4M91pwM7xDo" }
solana_monopoly = { path = "programs/solana-monopoly", address = "GPE95gXdq1Rv6obrv3kfJA4C3W6z27oRZhV8PEHwL7BK" }

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[registry]
url = "https://api.apr.dev"

[workspace]
members = [
    "programs/monopoly-world",
    "programs/components/common",
    "programs/components/game-state/game-state-component",
    "programs/components/player/player-component",
    "programs/components/position",
    "programs/components/property/property-component",
    "programs/systems/cards",
    "programs/systems/movement",
    "programs/systems/property"
]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "WorLD15A7CrDwLcLy4fRqtaTb9fbd8o8iqiEMUDse2n"
program = "tests/fixtures/world.so"
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://rpc.magicblock.app/devnet/"
ledger = ".bolt/test-ledger"
rpc_port = 8899

[[test.validator.account]]
address = "EHLkWwAT9oebVv9ht3mtqrvHhRVMKrt54tF3MfHTey2K"
filename = "tests/fixtures/registry.json"
